; MediStride Firmware
; Platform: XIAO ESP32-S3
; Framework: Arduino

[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

; BLE stack léger pour ESP32
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.1

; Flags de compilation
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; Décommenter pour activer l'IMU MPU-6050
    ; -DIMU_ENABLED

; Taille du partition scheme pour BLE
board_build.partitions = default.csv